### PR TITLE
Tests for getemployment and getprs

### PR DESCRIPTION
**Pull request by zefciu**
I did some refactoring. Used interfaces, so we can test with static data.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/statkube/18)

### CODE REVIEW

**Comment by nebril** [comment]
LGTM for now.

**Comment by zefciu** [comment]
@nebril @pigmej OK, finished the refactor and wrote the tests needed

**Comment by pigmej** [comment]
@zefciu looks ok but let's address @nebril concerns.

**Comment by zefciu** [comment]
Done

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/18#-:-KX552bpcs_EaMbtsxf_:bb6un1j)*

**Comment by pigmej** [comment]
:lgtm: 

@nebril can you verify it?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/18#-:-KX5LFm5mk4anUcK_YrY:b9xa1yb)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/18#-:-KX5xckdvEEz93hX_kWg:bnfp4nl)*

**Pull request merged**
