### PR TITLE
Support for multiple repositories

### PR DESCRIPTION
**Pull request by zefciu**
Added support for multiple repositories loaded from repos.json

Fixes: #11

---

This change is [Reviewable](https://reviewable.io/reviews/mirantis/statkube/16)

### CODE REVIEW

**Comment by pigmej** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/getemployment.go, line 135 at r1](https://reviewable.io:443/reviews/mirantis/statkube/16#-KV4yZy-ah6VyRjw0nsK:-KV4yZy-ah6VyRjw0nsL:b-scttoe) ([raw file](https://github.com/mirantis/statkube/blob/ed6e62481f75d257ec99e0b0f5e562bfa94b2827/cmd/getemployment.go#L135)):*
> ```Go
> func main() {
> 	db := db.GetDB()
> 	f, err := os.Open("repos.json")
> ```

make it ENV variable as `EMPLOYMENT_FILE`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16)*

**Comment by zefciu** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/getemployment.go, line 135 at r1](https://reviewable.io:443/reviews/mirantis/statkube/16#-KV4yZy-ah6VyRjw0nsK:-KV5HSgTTVO1AKX83YrQ:b-896fix) ([raw file](https://github.com/mirantis/statkube/blob/ed6e62481f75d257ec99e0b0f5e562bfa94b2827/cmd/getemployment.go#L135)):*
<details><summary><i>Previously, pigmej (Jędrzej Nowak) wrote…</i></summary>
> make it ENV variable as `EMPLOYMENT_FILE`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16)*

**Comment by pigmej** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/getemployment.go, line 135 at r1](https://reviewable.io:443/reviews/mirantis/statkube/16#-KV4yZy-ah6VyRjw0nsK:-KV5OBE1MXZ6foZh0KZq:b2nhktp) ([raw file](https://github.com/mirantis/statkube/blob/ed6e62481f75d257ec99e0b0f5e562bfa94b2827/cmd/getemployment.go#L135)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary>
> Done.
</details>
OK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16#-:-KV5OPZOd_eh_Nf7NT6-:bnfp4nl)*

**Comment by nebril** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[repos.json, line 1 at r2](https://reviewable.io:443/reviews/mirantis/statkube/16#-KVPETk4UROiaZPGsgy8:-KVPETk4UROiaZPGsgy9:b-1ephpf) ([raw file](https://github.com/mirantis/statkube/blob/2787f5acd2e43968512a52c031c5bdd1e07618b2/repos.json#L1)):*
> ```JSON
> [
> ```

Shouldn't we also be able to cover repos from outside of kubernetes org?

---

*[cmd/getemployment.go, line 139 at r2](https://reviewable.io:443/reviews/mirantis/statkube/16#-KVPF7NLywimEWuKKS5r:-KVPF7NLywimEWuKKS5s:b-p3pbba) ([raw file](https://github.com/mirantis/statkube/blob/2787f5acd2e43968512a52c031c5bdd1e07618b2/cmd/getemployment.go#L139)):*
> ```Go
> 		filename = "repos.json"
> 	}
> 	f, err := os.Open(filename)
> ```

Shouldn't we defer os.Close(filename) here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16)*

**Comment by zefciu** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[repos.json, line 1 at r2](https://reviewable.io:443/reviews/mirantis/statkube/16#-KVPETk4UROiaZPGsgy8:-KVPIcQSsjvFsezbViuM:b-yd4es8) ([raw file](https://github.com/mirantis/statkube/blob/2787f5acd2e43968512a52c031c5bdd1e07618b2/repos.json#L1)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary>
> Shouldn't we also be able to cover repos from outside of kubernetes org?
</details>
Not yet at least.

---

*[cmd/getemployment.go, line 139 at r2](https://reviewable.io:443/reviews/mirantis/statkube/16#-KVPF7NLywimEWuKKS5r:-KVPIhENaX2vHiNmEIEF:b-896fix) ([raw file](https://github.com/mirantis/statkube/blob/2787f5acd2e43968512a52c031c5bdd1e07618b2/cmd/getemployment.go#L139)):*
<details><summary><i>Previously, nebril (Maciej Kwiek) wrote…</i></summary>
> Shouldn't we defer os.Close(filename) here?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16)*

**Comment by pigmej** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[repos.json, line 1 at r2](https://reviewable.io:443/reviews/mirantis/statkube/16#-KVPETk4UROiaZPGsgy8:-KVRWIEV8a5X-fdqkarT:bpc8su0) ([raw file](https://github.com/mirantis/statkube/blob/2787f5acd2e43968512a52c031c5bdd1e07618b2/repos.json#L1)):*
<details><summary><i>Previously, zefciu (Szymon Pyżalski) wrote…</i></summary>
> Not yet at least.
</details>
Yeah, we're supporting now only kubernetes/* stuff, to have not only that we should support filtering it by groups in iface.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16)*

**Comment by pigmej** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16)*

**Comment by nebril** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/16#-:-KVZURCnOQQXvHXEQgbT:bnfp4nl)*

**Pull request merged**
