### PR TITLE
Added sleep to circumvent API limits

### PR DESCRIPTION
**Pull request by zefciu**
The getprs command will sleep through the periods of exhausted limits.

---
This change is [Reviewable](https://reviewable.io/reviews/mirantis/statkube/22)

### CODE REVIEW

**Comment by nebril** [comment]
It seems to work allright, but it's not testable at all. I would not merge this without tests, but other reviewers input is welcome.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/22#-:-KXpuITpeVU1oIKPHQva:b-2wgm3e)*

**Comment by zefciu** [comment]
Will unittest of CheckLimits suffice? Or do we need something higher level?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/22#-:-KXpwbb8ZHJMPj6jTgjS:b-wan37w)*

**Comment by zefciu** [comment]
Done

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/22#-:-KYDIONTJ9UkdkMGMaJj:bb6un1j)*

**Comment by zefciu** [comment]
@nebril PTAL

**Comment by nebril** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/22#-:-KYIWg6IBehTN8OX7CKy:bnfp4nl)*

**Comment by pigmej** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mirantis/statkube/22#-:-KYTFHrvWwV-LWzSF93O:bnfp4nl)*

**Pull request merged**
